# Generated by Django 5.2.13 on 2026-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
    ]
