# Generated by Django 5.2.13 on 2026-05-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.CharField(max_length=500, verbose_name='内容'),
        ),
    ]
